# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Lotus58 OLED Display
CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Copy pasting underglow code (mijn leds zijn SK6803 mini-e type RGB):
CONFIG_ZMK_RGB_UNDERGLOW=y
# Use the STRIP config specific to the LEDs you're using
CONFIG_WS2812_STRIP=y

# Volgende lijkt niet te werken:
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP = 10 # x percent brightness
#CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX = 50 # max percent brightness
#CONFIG_ZMK_RGB_UNDERGLOW_EFF_START = 2 # start effect, 0= solid 1= breathe 2= spectrum 3= swirl